# Generated by Django 5.0.1 on 2024-02-23 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField(blank=True, default=None, null=True)),
                ('required_branchs', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ENTC', 'ENTC'), ('Printing', 'Printing'), ('AIDS', 'AIDS')], default='', max_length=20)),
                ('location', models.CharField(default='', max_length=50)),
                ('system_time', models.DateTimeField()),
                ('required_CGPA', models.IntegerField(blank=True, default=None, null=True)),
                ('required_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('date_exam', models.DateTimeField(default=django.utils.timezone.now)),
                ('venue', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('crn_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ENTC', 'ENTC'), ('Printing', 'Printing'), ('AIDS', 'AIDS')], max_length=20)),
                ('year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('CGPA', models.IntegerField(blank=True, default=None, null=True)),
                ('mobile_number', models.CharField(default='', max_length=15)),
                ('mark_10th', models.IntegerField(blank=True, default=None, null=True)),
                ('mark_12th', models.IntegerField(blank=True, default=None, null=True)),
                ('diploma_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('aggregate_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('year_down', models.CharField(default='', max_length=5)),
                ('active_backlog', models.CharField(default='', max_length=15)),
                ('remarks', models.CharField(default='', max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvg.jobdetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvg.student')),
            ],
        ),
    ]
