# Generated by Django 4.1.3 on 2023-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crn_number', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('TE', 'Telecommunication Engineering'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ENTC', 'Electronics and Telecommunication Engineering')], max_length=10)),
                ('student_class', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('sem_marks_sheet', models.FileField(upload_to='sem_marks_sheets/')),
                ('cv_file', models.FileField(upload_to='cv_files/')),
            ],
        ),
    ]
