# Generated by Django 4.1.3 on 2023-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_branch', models.CharField(max_length=50)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
