# Generated by Django 5.0.1 on 2024-03-02 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='last_exam',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
