# Generated by Django 5.0.1 on 2024-03-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0002_jobdetail_last_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='last_exam',
            new_name='date_last',
        ),
    ]
