# Generated by Django 4.1.3 on 2024-01-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0004_rename_jobdetails_jobdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
