# Generated by Django 5.0.1 on 2024-03-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0005_jobapplication_is_present_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='placement_date',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='is_present',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
        migrations.AlterField(
            model_name='placement',
            name='job',
            field=models.CharField(max_length=100),
        ),
    ]
