# Generated by Django 4.1.3 on 2024-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0005_jobdetail_location_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='job_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('ME', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ENTC', 'Electronics and Telecommunication Engineering'), ('Printing', 'Printing'), ('AIDS', 'AIDS')], max_length=10),
        ),
    ]
