# Generated by Django 4.1.3 on 2024-01-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0006_jobdetail_job_id_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], default='', max_length=10),
        ),
    ]
