# Generated by Django 5.0.1 on 2024-03-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0007_alter_placement_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='job',
            new_name='company_name',
        ),
    ]
