# Generated by Django 4.1.3 on 2024-01-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0008_remove_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('ME', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ENTC', 'ENTC'), ('Printing', 'Printing'), ('AIDS', 'AIDS')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], default='', max_length=20),
        ),
    ]
