# Generated by Django 5.0.1 on 2024-03-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0009_placement_placement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='placement_status',
        ),
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
