# Generated by Django 4.1.3 on 2024-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0009_student_branch_alter_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
