# Generated by Django 4.1.3 on 2024-02-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0010_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='systemTime',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='CGPA',
            field=models.CharField(default='', max_length=4),
        ),
    ]
