# Generated by Django 4.1.3 on 2024-02-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0011_jobdetail_systemtime_student_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='job_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('ME', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ENTC', 'ENTC'), ('Printing', 'Printing'), ('AIDS', 'AIDS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='crn_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
