# Generated by Django 5.0.1 on 2024-03-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0011_rename_student_jobapplication_crn_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='crn_number',
            new_name='student',
        ),
    ]
