# Generated by Django 4.1.3 on 2024-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0012_remove_jobdetail_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='systemTime',
            new_name='system_time',
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], max_length=20),
        ),
    ]
