# Generated by Django 5.0.1 on 2024-02-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0013_rename_systemtime_jobdetail_system_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='crn_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
