# Generated by Django 5.0.1 on 2024-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0014_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
