# Generated by Django 5.0.1 on 2024-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0014_alter_student_crn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='system_time',
            field=models.DateTimeField(),
        ),
    ]
