# Generated by Django 5.0.1 on 2024-02-05 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0015_alter_jobdetail_job_id_alter_jobdetail_system_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvg.jobdetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvg.student')),
            ],
        ),
    ]
