# Generated by Django 5.0.1 on 2024-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0015_alter_jobdetail_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='required_CGPA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
