# Generated by Django 5.0.1 on 2024-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0017_alter_admin_admin_email_alter_jobdetail_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passing_year',
            field=models.IntegerField(default=0),
        ),
    ]
