# Generated by Django 5.0.1 on 2024-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvg', '0018_student_passing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='required_passing_year',
            field=models.IntegerField(default=2024),
        ),
    ]
